language: elixir

elixir:
  - 1.6.1

addons:
  postgresql: '9.4'

services:
  - postgresql

before_install:
  - cp config/travis.exs config/test.exs

before_script:
  - mix local.hex --force
  - mix do ecto.create, ecto.migrate

script:
  - mix test