language: elixir

elixir:
  - 1.4.1

addons:
  postgresql: '9.4'

services:
  - postgresql

before_install:
  - cp config/travis.exs config/test.exs
  - cp config/travis.secret.exs config/dev.secret.exs
  - mix do ecto.create, ecto.migrate

script:
  - mix test