name: Phoenix Dialyzer

on: push

jobs:
  test:
    runs-on: ubuntu-16.04

    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-deps-dialyzer-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-deps-dialyzer-
      - uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-dialyzer-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-dialyzer-
      - uses: actions/cache@v1
        with:
          path: assets/node_modules
          key: ${{ runner.os }}-node_modules-dialyzer-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-dialyzer-
      - run: cp config/dev.secret.exs.example config/dev.secret.exs
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: 22.1
          elixir-version: 1.9.1
      - run: mix deps.get
      - run: MIX_ENV=dev mix check --only dialyzer
